require("charlie.plugins-setup")
require("charlie.core.options")
require("charlie.core.keymaps")
require("charlie.core.colorscheme")
require("charlie.plugins.comment")
require("charlie.plugins.nvim-tree")
require("charlie.plugins.lualine")
require("charlie.plugins.telescope")
require("charlie.plugins.nvim-cmp")
require("charlie.plugins.lsp.lspsaga")
require("charlie.plugins.metals")
require("charlie.plugins.lsp.mason")
require("charlie.plugins.lsp.config")
require("charlie.plugins.lsp.null_ls")
require("charlie.plugins.autopairs")
require("charlie.plugins.treesitter")
require("charlie.plugins.git")

